<?php

/**
 * @description :
 * @Author: 王广鑫
 * @Date: 2019/8/10 8:52
 * @package console\controller
 */


namespace console\controllers;

use johnnylei\redis_queue;
use console\models\Goods;
use yii\console\Controller;

class TestController extends Controller
{
    private $redis = null;
    public function beforeAction($action)
    {

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $this->redis = new \Redis();
        $this->redis->connect('127.0.0.1',6379);
        $this->redis->select(4);
        $this->redis->setOption(\Redis::OPT_READ_TIMEOUT,-1);
        $this->redis->psubscribe(array('__keyevent@0__:expired'), [$this,'Callback']);
    }
    public function actionCallback()
    {
        echo 1;
    }

}